### ISSUE TITLE
*** [upload] Error 3221225477

### ISSUE THREAD

**Issue by X3msnake** [positron96/cnc3018-offline-controller#12]
Any idea why this error?

Building in release mode
Checking size .pio\build\controller\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  46.3% (used 9484 bytes from 20480 bytes)
Flash: [=====     ]  51.9% (used 68040 bytes from 131072 bytes)
Configuring upload protocol...
AVAILABLE: blackmagic, cmsis-dap, dfu, jlink, serial, stlink
CURRENT: upload_protocol = stlink
Uploading .pio\build\controller\firmware.elf
xPack OpenOCD x86_64 Open On-Chip Debugger 0.11.0+dev (2021-10-16-21:19)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 1

0x20000
hla_swd
*** [upload] Error 3221225477

**Comment by positron96** [comment]
Hi. Sorry for long response. No, I've not encountered this error

**Comment by X3msnake** [comment]
I found out why, the ic is the stm clone, what i ended up doing was getting some real stm chips and replacing the ic on the board.
it worked that way

**Comment by X3msnake** [comment]
![IMG_20221214_035853](https://user-images.githubusercontent.com/11083514/216609555-c3379499-7fd5-4621-acc2-083d904a257c.jpg)
![IMG_20221214_013853](https://user-images.githubusercontent.com/11083514/216609567-fad4fd3d-f3e0-4d04-94d8-d6dcf59c30d9.jpg)
![IMG_20221214_035945](https://user-images.githubusercontent.com/11083514/216609582-60c18172-1317-42cb-8de1-a6eb28277fad.jpg)

**Comment by X3msnake** [comment]
One has to remove the oled first or burn it like i did. had to replace it also :P

**Comment by positron96** [comment]
Oh, sorry for the display. Do you know why it got burned? And what replacement did you order?

**Comment by X3msnake** [comment]
its the basic oled 2.8 ones you can get on ebay and aliexpress for cheap, no worries i had some around, just dessoldered one and resoldered it and ir works fine. 

It is one of those basic slap in the forehead things that happens :D

Btw good job you did with the firmware, thanks for sharing
