### ISSUE TITLE
Impossible to flash APM32F103RBT6 chip

### ISSUE THREAD

**Issue by RepRapThailand** [positron96/cnc3018-offline-controller#13]
Hi,

 My hardware is APM32F103RBT6.

![1675398582392](https://user-images.githubusercontent.com/15525407/216512852-de4f4cbb-2193-4a56-8268-51db58a7eb24.jpg)
![37279](https://user-images.githubusercontent.com/15525407/216512474-8e58101d-0939-4232-b9ab-4fdb92078236.jpg)
![37280](https://user-images.githubusercontent.com/15525407/216512481-7d752dfa-de15-4db7-bcaa-c4422c55c006.jpg)

Thank you.

**Comment by positron96** [comment]
Hi. I've never heard of this chip and how to flash it. Also, I am afraid this project does not support your hardware, as it seem to contain a full-color TFT display (and a microSD slot which usually indicates a newer hardware with a TFT display). So you are on your own, sorry.

**Comment by RepRapThailand** [comment]
Hi, 
for chip
https://www.sunrom.com/p/apm32f103rbt6-lqfp64-geehy-arm-cortex-m3-replacement-for-stm32f103rbt6
my display is OLED.

**Comment by positron96** [comment]
Thank you for the info. However, I have no experience with this chip, so can only give limited advice. Actually your MCU should have 128kb officially, while the original STM32F103 only had 64k officially, that might be the difference in settings. You could probably compile the firmware for STM32F103RBT6 and try to upload that.

Also, you'd better check that schematic of your board matches one used in the firmware. As the SD slot is different on your board, there might be other differences.
