### ISSUE TITLE
Incorrect Labeling for the SWDIO Interface Pins?

### ISSUE THREAD

**Issue by StefanLilje** [positron96/cnc3018-offline-controller#15]
I had just started reverse engineering my own little Controller (which seems to be identical to the one shown), when I stumbled across this awesome repository. However  the Pin furthest from the Edge, which is labeled +5V, seems to be connected directly to the supply pins of the STM32F103, aswell as the output of the regulator (at least on my board). Am I missing something here or is it misslabeled as +5V?

**Comment by positron96** [comment]
Oh.
Yes, I checked it now, and I believe you are totally correct! Thanks for noticing, I'll fix it in the schematic soon.
