### ISSUE TITLE
[Question] Another offline-contorller from AliExpress

### ISSUE THREAD

**Issue by maxl95** [positron96/cnc3018-offline-controller#2]
Hey guys,

I also recently bought a 3018 CNC. An offline controller was also included. But this one has an STM32F103RBT6. That means I shouldn't try this firmware, right?

regards maxl95

**Comment by maxl95** [comment]
Sorry, I forgot the photo

![offlinecontroller](https://user-images.githubusercontent.com/15520385/138091129-254fb915-c1e9-4eb2-b3a1-27cbaedcb85b.jpg)
o

**Comment by positron96** [comment]
Hi. This looks like a controller with a colored TFT display, which is totally different from the OLED display in the controller I have. So, I'm afraid, my firmware will not work with this board.

**Comment by maxl95** [comment]
Thank you for your quick response. Yes, you're right, it has a colored display. The firmware on the Controller is very bad. I thought I could improve it with your firmware. Unfortunately the read-out protection is activated. So I can't make a backup and make firmware myself.

**Comment by Jempiken** [comment]
Hello Max195.. I have the same as yours...  I bricked mine, trying to upload the firmware... from positron
Any chance that I could have the firmware for it.. ??
I first read it though, but When i read it with ST-linkv2  the memory starts at 0x08000000 for 0x3F54 Bytes
It is a lot less bytes.. than the original.hex from positron.
Can you try to read it..
The SW settings is slow speed at 480kHz and the it connects OK ! but only reading from that adress
Tnx 4 help
JP

**Comment by Jempiken** [comment]
I t can be read, probably I read too little...  i had to read the full data range, but did not..
I used a white ST-LINK V2
JP

**Comment by zolo2hin** [comment]
@Jempiken. @maxl95 guys have you any updates with that? May be we should try to make some branch and start to do from scratch?
